/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import javax.swing.JOptionPane;

/**
 *
 * @author Emilio
 */
public class FrmIndex extends javax.swing.JFrame {

    /**
     * Creates new form FrmIndex
     */
    public FrmIndex() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEjer2 = new javax.swing.JButton();
        btnEjer1 = new javax.swing.JButton();
        btnEjer3 = new javax.swing.JButton();
        btnEjer4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEjer2.setBackground(new java.awt.Color(255, 153, 51));
        btnEjer2.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        btnEjer2.setText("Ejercicio 2");
        btnEjer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjer2ActionPerformed(evt);
            }
        });

        btnEjer1.setBackground(new java.awt.Color(255, 153, 51));
        btnEjer1.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        btnEjer1.setText("Ejercicio 1");
        btnEjer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjer1ActionPerformed(evt);
            }
        });

        btnEjer3.setBackground(new java.awt.Color(255, 153, 51));
        btnEjer3.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        btnEjer3.setText("Ejercicio 3");
        btnEjer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjer3ActionPerformed(evt);
            }
        });

        btnEjer4.setBackground(new java.awt.Color(255, 153, 51));
        btnEjer4.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        btnEjer4.setText("Ejercicio 4");
        btnEjer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEjer3)
                    .addComponent(btnEjer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEjer2)
                    .addComponent(btnEjer4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjer2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjer1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjer3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjer4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjer1ActionPerformed
        FrmEjercicio1 openForm = new FrmEjercicio1();
        openForm.setVisible(true);
    }//GEN-LAST:event_btnEjer1ActionPerformed

    private void btnEjer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjer2ActionPerformed
        FrmEjercicio2 openForm = new FrmEjercicio2();
        openForm.setVisible(true);
    }//GEN-LAST:event_btnEjer2ActionPerformed

    private void btnEjer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjer3ActionPerformed
        FrmEjercicio3 openForm = new FrmEjercicio3();
        openForm.setVisible(true);
    }//GEN-LAST:event_btnEjer3ActionPerformed

    private void btnEjer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjer4ActionPerformed
           JOptionPane.showMessageDialog(this, "Profe este sinceramente no se pudo, lo siento");
    }//GEN-LAST:event_btnEjer4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjer1;
    private javax.swing.JButton btnEjer2;
    private javax.swing.JButton btnEjer3;
    private javax.swing.JButton btnEjer4;
    // End of variables declaration//GEN-END:variables
}
